### ISSUE TITLE
bcrypt compare always return fall

### ISSUE THREAD

**Issue by rickdana** [shaneGirish/bcrypt-nodejs#36]
Hello, 
I'm implementing an user auth with Bcrypt. 
I'm facing an issue when comparing the given password with the one store in my DB i always have a false message.
here is my compare method :

 bcrypt.compare(param.motdepasse , client.motdepasse, function(err, pass) {
                if(err) res.json(200,{Message :'Error'});
                if(pass == true){
                    client.isAuthenticate = 'true';
                    res.json(client);
                }else{
                   res.json(200,{Message :'Mot de passe érronée !'});
                }

      });

Please any idea? thk!

**Comment by rickdana** [comment]
thank u i got it solve. the problem was the length of my password in my db

**Comment by prabodh1194** [comment]
Length Alert :)
