### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by derbl4ck** [shaneGirish/bcrypt-nodejs#42]
I use Windows 7. Here is my error:

D:\alles\Documents_tellize\feed>npm install
npm WARN package.json path@0.11.14 path is also the name of a node core module.

> bcrypt@0.8.0 install D:\alles\Documents_tellize\feed\node_modules\bcrypt
> node-gyp rebuild

D:\alles\Documents_tellize\feed\node_modules\bcrypt>node "C:\Program Files (x86
)\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node
-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB3411: Die Visual C++-Komponente "VCBuild.exe" konnte nicht g
eladen werden. Wenn die Komponente installiert ist, fügen Sie deren Speicherort
dem Systempfad hinzu. Wenn sie nicht installiert ist, 1) installieren Sie entw
eder das Microsoft Windows SDK für Windows Server 2008 und .NET Framework 3.5 o
der 2) Microsoft Visual Studio 2008.  [D:\alles\Documents_tellize\feed\node_mo
dules\bcrypt\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\nod
e_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\alles\Documents_tellize\feed\node_modules\bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (
x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\alles\Documents_tellize\feed\npm-debug.log

**Comment by butterkekstorte** [comment]
The error is from bcrypt. That's a different module!
