### ISSUE TITLE
bcrypt compare returns false all the time

### ISSUE THREAD

**Issue by justinjwlee** [shaneGirish/bcrypt-nodejs#45]
Hi there,

I'm implementing user authentication using bcrypt. Bcrypt compare is returning false despite the password being correct. Interestingly, bcrypt compare works on a local db but not on a hosted remote db. (not a password string length issue) Any idea what might be the problem?

```
UserSchema.methods.validPassword = function (password, next) {
	var user = this;

	bcrypt.compare(password, user.password, function (err, isMatch) {
		if (err) {
			console.log('PW COMPARE ERR: Validation process failed')
			next(err)
		};
		
		next(null, isMatch)
	})
};
```

**Comment by justinjwlee** [comment]
Sorry it was entirely my own issue. Rectified & closed

**Comment by ms88privat** [comment]
i am faceing the same problem - what was your mistake? maybe its mine too...

**Comment by justinjwlee** [comment]
if you're using mongoose and using bcrypt hash in the pre-save method of
mongoose in the models, make sure in your function you're only calling
'save' once. If not hash will be called more than once which will naturally
fail bcrypt compare.

Again, this is my own error entirely unrelated to bcrypt

**Comment by PsyEnmanuel** [comment]
thanks you, i was having a similar mistake.
