### ISSUE TITLE
Standardized license

### ISSUE THREAD

**Issue by davidbarton** [shaneGirish/bcrypt-nodejs#69]
Hello, can you please use standardized license for project and also add it to `package.json`

**Comment by zurfyx** [comment]
@davidbarton and other visitors:

Consider switching to [bcrypt](https://www.npmjs.com/package/bcrypt). This library hasn't been updated in ~2 years, whilst [bcrypt](https://www.npmjs.com/package/bcrypt) is being updated in a monthly basis.
The source code changes are minimal.

**Comment by zurfyx** [comment]
@davidbarton and other visitors:

Consider switching to [bcrypt](https://www.npmjs.com/package/bcrypt). This library hasn't been updated in ~2 years, whilst [bcrypt](https://github.com/kelektiv/node.bcrypt.js) is being updated in a monthly basis.
The source code changes are minimal.

**Comment by cmawhorter** [comment]
This seems like an option https://github.com/dcodeIO/bcrypt.js

**Comment by davidbarton** [comment]
Yup already using it, it's great package.
