### ISSUE TITLE
Please mark the npm package / this project as deprecated

### ISSUE THREAD

**Issue by YasharF** [shaneGirish/bcrypt-nodejs#83]
In the repo you have stated that "This project is not actively maintained"  Can you please push a deprecation message to npm's repo.  I suspect you would need to run the following:

`npm deprecate bcrypt-nodejs "bcrypt-nodejs is no longer actively maintained.  Please use bcrypt or bcryptjs.  See https://github.com/kelektiv/node.bcrypt.js/wiki/bcrypt-vs-brypt.js to learn more about these two options"`

Ref: https://docs.npmjs.com/cli/deprecate

**Comment by YasharF** [comment]
You may also want to consider archiving this github repo afterward:  [https://help.github.com/en/articles/archiving-a-github-repository](https://help.github.com/en/articles/archiving-a-github-repository)

Thank you!

**Comment by YasharF** [comment]
@joshball , @shaneGirish
Both of you seem to have been listed by the npm repo as the owners of the package.  Can you please help with officially deprecating the npm package and this repo?

- This github repo already has a text stating "Note: This project is not actively maintained"
- The npm package was last published 6 years ago.
- The npm package is currently getting 60K weekly downloads because other developers don’t realize it is deprecated and is unmaintained. There are 746 npm packages that have bcrypt-noedjs listed as a dependency but don’t know about the deprecation listed on the github page.  This github page is not even connected to npm anymore, and the link on npm results in a 404 error.


Thanks

**Comment by YasharF** [comment]
Update 4/17/219: I sent an email to @joshball , @shaneGirish 's email addresses listed in the npm's package repo, in case if they are no longer receiving notifications from GitHub.

**Comment by joshball** [comment]
@YasharF 
I apologize, I had not seen these notifications. I will handle this today.

**Comment by joshball** [comment]
@YasharF 
Thank you for pursuing this. The package is now deprecated (because of your persistence!)

![image](https://user-images.githubusercontent.com/127526/57541064-6a7e3000-730b-11e9-9651-c1510b227330.png)
